---
- include: Debian.yml
  when: ansible_os_family == 'Debian'
  tags: package

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: package

- name: configure zabbix agent
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent

- name: run zabbix agent
  service: name=zabbix-agent state=running enabled=yes
