---
- name: install zabbix agent
  apt: pkg=zabbix-agent state={{ zabbix_agent_pkg_state }}
  when: ansible_os_family == 'Debian'
  tags: package

- name: install zabbix agent
  yum: name=zabbix-agent state={{ zabbix_agent_pkg_state }}
  when: ansible_os_family == 'RedHat'
  tags: package

- name: configure zabbix agent
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent
  tags: configuration

- name: start/stop zabbix agent
  service: name=zabbix-agent state={{ zabbix_agent_service_state }} enabled={{ zabbix_agent_service_enabled }}
  tags: service
